const ads = [
  {
    1: {
      banner: {
        name: "Sai",
        clinicName: "Cool Clinic",
        phoneNumber: 8956471230,
      },
      templateId: 1,
      adId: 7779779898,
      doctorId: "1",
      submittedBy: "doctor",
      targetDistrict: ["Jabalpur", "Central Delhi"],
      targetState: ["Madhya Pradesh", "Delhi (NCT)"],
      duration: 30,
      approvedBy: "Akash",
      startDate: "2022-10-21",
      status: "approved",
      endDate: "2022-10-11",
      billing: 800,
      clicks: 100,
      appearances: 1000,
    },
  },
  {
    2: {
      banner: {
        name: "Sai",
        clinicName: "Cool Clinic",
        phoneNumber: 8956471230,
      },
      templateId: 1,
      adId: 7779779898,
      doctorId: "1",
      submittedBy: "doctor",
      targetDistrict: ["Puri", "Jabalpur"],
      targetState: ["Madhya Pradesh", "Odisha"],
      duration: 30,
      approvedBy: "Akash",
      startDate: "2022-11-21",
      status: "running",
      endDate: "2022-11-26",
      billing: 800,
      clicks: 10,
      appearances: 10,
    },
  },
  {
    3: {
      banner: {
        name: "Sai",
        clinicName: "Cool Clinic",
        phoneNumber: 8956471230,
      },
      templateId: 1,
      adId: 7779779898,
      doctorId: "1",
      submittedBy: "doctor",
      targetDistrict: ["Balasore", "Pune"],
      targetState: ["Maharashtra", "Odisha"],
      duration: 30,
      approvedBy: "Akash",
      startDate: "2022-12-21",
      status: "approved",
      endDate: "2022-12-29",
      billing: 800,
      clicks: 22,
      appearances: 150,
    },
  },
  {
    4: {
      banner: {
        name: "Ayush",
        clinicName: "Cool cool Clinic",
        phoneNumber: 8956471230,
      },
      templateId: 6,
      adId: 7779779898,
      doctorId: "2",
      submittedBy: "doctor",
      targetDistrict: ["Lucknow", "Balasore"],
      targetState: ["Uttar Pradesh", "Odisha"],
      duration: 30,
      approvedBy: "AkashG",
      startDate: "2022-09-21",
      status: "approved",
      endDate: "2022-09-29",
      billing: 800,
      clicks: 252,
      appearances: 1540,
    },
  },
  {
    5: {
      banner: {
        name: "Nitish",
        clinicName: "Cool cool Clinic",
        phoneNumber: 8956471230,
      },
      templateId: 2,
      adId: 7779779898,
      doctorId: "1",
      submittedBy: "doctor",
      targetDistrict: ["Lucknow", "Jabalpur"],
      targetState: ["Uttar Pradesh", "Madhya Pradesh"],
      duration: 30,
      approvedBy: "Sachin",
      startDate: "2022-08-21",
      status: "approved",
      endDate: "2022-08-29",
      billing: 800,
      clicks: 22,
      appearances: 150,
    },
  },
];

module.exports = { ads };
